---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-svc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
  - port: 3000
    targetPort: 80
    protocol: TCP
